[build]
  command = "npm run generate; netlify-lambda build lambda"
  functions = "functions"

[context.production.environment]
  IS_DEV = "false"

[context.deploy-preview.environment]
  IS_DEV = "true"

[context.branch-deploy.environment]
  IS_DEV = "true"
