[build]
  command = "npm run generate; npm run build:lambda"
  functions = "lambda"
  publish = "functions"

[context.production]
  command = 'export MY_ENV="HELLO"; npm run generate;'
  [environment]
    IS_DEV = "false"
    NODE_ENV = "development"

[context.deploy-preview.environment]
  IS_DEV = "true"
  NODE_ENV = "development"

[context.branch-deploy.environment]
  IS_DEV = "true"
  NODE_ENV = "development"
