[build]
  command = "npm run generate; netlify-lambda build lambda"
  functions = "functions"

[context.production]
  command = './setenv.sh; npm run generate; netlify-lambda build lambda'
  [environment]
    IS_DEV = "false"
    NODE_ENV = "development"

[context.deploy-preview.environment]
  IS_DEV = "true"
  NODE_ENV = "development"

[context.branch-deploy.environment]
  IS_DEV = "true"
  NODE_ENV = "development"
